# Generated by Django 5.0.7 on 2025-06-08 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_order', models.IntegerField()),
                ('drafted_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='players.player')),
                ('fantasy_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='fantasy.fantasyteam')),
            ],
            options={
                'ordering': ['draft_order'],
                'unique_together': {('fantasy_team', 'draft_order')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='players.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'player')},
            },
        ),
    ]
