# Generated by Django 5.0.7 on 2025-06-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('points_per_game', models.FloatField(default=0.0)),
                ('rebounds_per_game', models.FloatField(default=0.0)),
                ('assists_per_game', models.FloatField(default=0.0)),
                ('steals_per_game', models.FloatField(default=0.0)),
                ('blocks_per_game', models.FloatField(default=0.0)),
                ('field_goal_percentage', models.FloatField(default=0.0)),
                ('three_point_percentage', models.FloatField(default=0.0)),
                ('free_throw_percentage', models.FloatField(default=0.0)),
                ('tournament_points', models.IntegerField(default=0)),
                ('tournament_games', models.IntegerField(default=0)),
                ('is_drafted', models.BooleanField(default=False)),
                ('drafted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
            options={
                'ordering': ['-points_per_game', 'name'],
                'unique_together': {('name', 'team')},
            },
        ),
    ]
