# Generated by Django 5.0.7 on 2025-06-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('seed', models.IntegerField()),
                ('region', models.CharField(choices=[('EAST', 'East'), ('WEST', 'West'), ('SOUTH', 'South'), ('MIDWEST', 'Midwest')], max_length=10)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('conference', models.CharField(blank=True, max_length=50)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('eliminated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['seed', 'name'],
                'unique_together': {('seed', 'region')},
            },
        ),
    ]
